//////////////////////////////////////////////////////////////////////
// C++ header file generated by SpecC V2.2.1
// Design: susan_edge_detector
// File:   susan_edge_detector.h
// Time:   Sun Nov  1 11:09:59 2015
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include <specc.h>

// named user-defined type declarations //////////////////////////////

struct timeval;

#line 65 "/usr/include/gconv.h"
struct __gconv_loaded_object;

#line 22 "susan_edge_detector.h"
struct __gconv_trans_data;
struct __gconv_step;
struct __gconv_step_data;
struct __gconv_info;

#line 167 "/usr/include/libio.h"
struct _IO_jump_t;

#line 31 "susan_edge_detector.h"
struct _IO_marker;
struct _IO_FILE;

#line 341 "/usr/include/libio.h"
struct _IO_FILE_plus;

#line 38 "susan_edge_detector.h"
struct exception;
struct random_data;
struct drand48_data;
struct timespec;
struct __pthread_internal_slist;

// named enumerator type definitions /////////////////////////////////

#line 203 "/usr/include/libio.h"
enum __codecvt_result {

    __codecvt_ok=0,
    __codecvt_partial=1,
    __codecvt_error=2,
    __codecvt_noconv=3
};

// unnamed enumerator type definitions ///////////////////////////////

#line 38 "/usr/include/gconv.h"
enum {
    __GCONV_OK=0,
    __GCONV_NOCONV=1,
    __GCONV_NODB=2,
    __GCONV_NOMEM=3,

    __GCONV_EMPTY_INPUT=4,
    __GCONV_FULL_OUTPUT=5,
    __GCONV_ILLEGAL_INPUT=6,
    __GCONV_INCOMPLETE_INPUT=7,

    __GCONV_ILLEGAL_DESCRIPTOR=8,
    __GCONV_INTERNAL_ERROR=9
};




enum {
    __GCONV_IS_LAST=1,
    __GCONV_IGNORE_ERRORS=2
};

#line 285 "/usr/include/math.h"
typedef enum {
    _IEEE_=-1,
    _SVID_=0,
    _XOPEN_=1,
    _POSIX_=2,
    _ISOC_=3 }
    _LIB_VERSION_TYPE;

// struct/union type definitions /////////////////////////////////////

#line 77 "/usr/include/wchar.h"
typedef struct {
    int __count;




    union { unsigned int __wch; char __wchb[4]; } __value; }
    __mbstate_t;

#line 27 "/usr/include/_G_config.h"
typedef struct {
    long int __pos;
    __mbstate_t __state; }
    _G_fpos_t;

#line 63 "/usr/include/bits/types.h"
typedef struct {
    long int __val[2]; }
    __quad_t;

#line 32 "/usr/include/_G_config.h"
typedef struct {
    __quad_t __pos;
    __mbstate_t __state; }
    _G_fpos64_t;

#line 145 "/usr/include/gconv.h"
struct __gconv_step_data {

    unsigned char *__outbuf;
    unsigned char *__outbufend;



    int __flags;



    int __invocation_counter;



    int __internal_use;

    __mbstate_t *__statep;
    __mbstate_t __state;



    struct __gconv_trans_data *__trans;
};



struct __gconv_info {

    unsigned int __nsteps;
    struct __gconv_step *__steps;
    struct __gconv_step_data __data[1];
};

#line 46 "/usr/include/_G_config.h"
typedef union {
    struct __gconv_info __cd;




    struct { struct __gconv_info __cd; struct __gconv_step_data __data; } __combined; }
    _G_iconv_t;

#line 29 "/usr/include/bits/sigset.h"
typedef struct {
    unsigned long int __val[32]; }
    __sigset_t;

#line 69 "/usr/include/bits/time.h"
struct timeval {

    long int tv_sec;
    long int tv_usec;
};

#line 67 "/usr/include/bits/types.h"
typedef struct {
    unsigned long int __val[2]; }
    __u_quad_t;

#line 147 "/usr/include/bits/types.h"
typedef struct { int __val[2]; } __fsid_t;

#line 103 "/usr/include/gconv.h"
struct __gconv_trans_data {


    int (*__trans_fct)(struct __gconv_step *, struct __gconv_step_data *, void *, const unsigned char *, const unsigned char **, const unsigned char *, unsigned char **, unsigned int *);
    int (*__trans_context_fct)(void *, const unsigned char *, const unsigned char *, unsigned char *, unsigned char *);
    void (*__trans_end_fct)(void *);
    void *__data;
    struct __gconv_trans_data *__next;
};



struct __gconv_step {

    struct __gconv_loaded_object *__shlib_handle;
    const char *__modname;

    int __counter;

    char *__from_name;
    char *__to_name;

    int (*__fct)(struct __gconv_step *, struct __gconv_step_data *, const unsigned char **, const unsigned char *, unsigned char **, unsigned int *, int, int);
    unsigned int (*__btowc_fct)(struct __gconv_step *, unsigned char);
    int (*__init_fct)(struct __gconv_step *);
    void (*__end_fct)(struct __gconv_step *);



    int __min_needed_from;
    int __max_needed_from;
    int __min_needed_to;
    int __max_needed_to;


    int __stateful;

    void *__data;
};

#line 183 "/usr/include/libio.h"
struct _IO_marker {
    struct _IO_marker *_next;
    struct _IO_FILE *_sbuf;



    int _pos;
};

#line 268 "/usr/include/libio.h"
struct _IO_FILE {
    int _flags;




    char *_IO_read_ptr;
    char *_IO_read_end;
    char *_IO_read_base;
    char *_IO_write_base;
    char *_IO_write_ptr;
    char *_IO_write_end;
    char *_IO_buf_base;
    char *_IO_buf_end;

    char *_IO_save_base;
    char *_IO_backup_base;
    char *_IO_save_end;

    struct _IO_marker *_markers;

    struct _IO_FILE *_chain;

    int _fileno;



    int _flags2;

    long int _old_offset;



    unsigned short int _cur_column;
    char _vtable_offset;
    char _shortbuf[1];



    void *_lock;

#line 316 "/usr/include/libio.h"
    __quad_t _offset;

#line 325 "/usr/include/libio.h"
    void *__pad1;
    void *__pad2;
    void *__pad3;
    void *__pad4;
    unsigned int __pad5;

    int _mode;

    char _unused2[40];
};

#line 309 "/usr/include/math.h"
struct exception {


    int type;
    char *name;
    double arg1;
    double arg2;
    double retval;
};

#line 99 "/usr/include/stdlib.h"
typedef struct {
    int quot;
    int rem; }
    div_t;




typedef struct {
    long int quot;
    long int rem; }
    ldiv_t;

#line 467 "/usr/include/stdlib.h"
struct random_data {

    int *fptr;
    int *rptr;
    int *state;
    int rand_type;
    int rand_deg;
    int rand_sep;
    int *end_ptr;
};

#line 536 "/usr/include/stdlib.h"
struct drand48_data {

    unsigned short int __x[3];
    unsigned short int __old_x[3];
    unsigned short int __c;
    unsigned short int __init;
    unsigned long long int __a;
};

#line 68 "/usr/include/sys/select.h"
typedef struct {

#line 75 "/usr/include/sys/select.h"
    long int __fds_bits[32]; }


    fd_set;

#line 121 "/usr/include/time.h"
struct timespec {

    long int tv_sec;
    long int tv_nsec;
};

#line 43 "/usr/local/packages/sce-20100908/inc/bits/huge_val.h"
typedef union { unsigned char __c[8]; double __d; } __huge_val_t;

#line 54 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef union {
    char __size[36];
    long int __align; }
    pthread_attr_t;

#line 67 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
struct __pthread_internal_slist {

    struct __pthread_internal_slist *__next;
};

#line 77 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef union {

#line 101 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
    struct __pthread_mutex_s { int __lock; unsigned int __count; int __owner; int __kind; unsigned int __nusers; union { int __spins; struct __pthread_internal_slist __list; } dummy; } __data;
    char __size[24];
    long int __align; }
    pthread_mutex_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_mutexattr_t;

#line 116 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef union {

#line 130 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __futex; unsigned long int dummy1; unsigned long int dummy2; unsigned long int dummy3; unsigned long int dummy4; unsigned long int dummy5; unsigned long int dummy6; void *__mutex; unsigned int __nwaiters; unsigned int __broadcast_seq; } __data;
    char __size[48];
    long long int __align; }
    pthread_cond_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_condattr_t;

#line 154 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef union {

#line 188 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
    struct { int __lock; unsigned int __nr_readers; unsigned int __readers_wakeup; unsigned int __writer_wakeup; unsigned int __nr_readers_queued; unsigned int __nr_writers_queued; unsigned char __flags; unsigned char __shared; unsigned char __pad1; unsigned char __pad2; int __writer; } __data;

    char __size[32];
    long int __align; }
    pthread_rwlock_t;


typedef union {
    char __size[8];
    long int __align; }
    pthread_rwlockattr_t;

#line 210 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef union {
    char __size[20];
    long int __align; }
    pthread_barrier_t;


typedef union {
    char __size[4];
    int __align; }
    pthread_barrierattr_t;

// type synonym definitions //////////////////////////////////////////

#line 55 "/usr/include/_G_config.h"
typedef int _G_int16_t;
typedef int _G_int32_t;
typedef unsigned int _G_uint16_t;
typedef unsigned int _G_uint32_t;

#line 23 "/usr/include/bits/sigset.h"
typedef int __sig_atomic_t;

#line 34 "/usr/include/bits/types.h"
typedef unsigned char __u_char;
typedef unsigned short int __u_short;
typedef unsigned int __u_int;
typedef unsigned long int __u_long;


typedef char __int8_t;
typedef unsigned char __uint8_t;
typedef short int __int16_t;
typedef unsigned short int __uint16_t;
typedef int __int32_t;
typedef unsigned int __uint32_t;

#line 138 "/usr/include/bits/types.h"
typedef unsigned int __uid_t;
typedef unsigned int __gid_t;
typedef unsigned long int __ino_t;

typedef unsigned int __mode_t;
typedef unsigned int __nlink_t;
typedef long int __off_t;

typedef int __pid_t;

typedef long int __clock_t;
typedef unsigned long int __rlim_t;

typedef unsigned int __id_t;
typedef long int __time_t;
typedef unsigned int __useconds_t;
typedef long int __suseconds_t;

typedef int __daddr_t;
typedef long int __swblk_t;
typedef int __key_t;


typedef int __clockid_t;


typedef void *__timer_t;


typedef long int __blksize_t;




typedef long int __blkcnt_t;



typedef unsigned long int __fsblkcnt_t;



typedef unsigned long int __fsfilcnt_t;


typedef int __ssize_t;




typedef __quad_t *__qaddr_t;
typedef char *__caddr_t;


typedef int __intptr_t;


typedef unsigned int __socklen_t;

#line 70 "/usr/include/gconv.h"
typedef int (*__gconv_fct)(struct __gconv_step *, struct __gconv_step_data *, const unsigned char **, const unsigned char *, unsigned char **, unsigned int *, int, int);




typedef unsigned int (*__gconv_btowc_fct)(struct __gconv_step *, unsigned char);


typedef int (*__gconv_init_fct)(struct __gconv_step *);
typedef void (*__gconv_end_fct)(struct __gconv_step *);



typedef int (*__gconv_trans_fct)(struct __gconv_step *, struct __gconv_step_data *, void *, const unsigned char *, const unsigned char **, const unsigned char *, unsigned char **, unsigned int *);

#line 91 "/usr/include/gconv.h"
typedef int (*__gconv_trans_context_fct)(void *, const unsigned char *, const unsigned char *, unsigned char *, unsigned char *);




typedef int (*__gconv_trans_query_fct)(const char *, const char ***, unsigned int *);



typedef int (*__gconv_trans_init_fct)(void **, const char *);
typedef void (*__gconv_trans_end_fct)(void *);

#line 177 "/usr/include/gconv.h"
typedef struct __gconv_info *__gconv_t;

#line 177 "/usr/include/libio.h"
typedef void _IO_lock_t;

#line 338 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;

#line 361 "/usr/include/libio.h"
typedef int __io_read_fn(void *, char *, unsigned int);

#line 369 "/usr/include/libio.h"
typedef int __io_write_fn(void *, const char *, unsigned int);

#line 378 "/usr/include/libio.h"
typedef int __io_seek_fn(void *, __quad_t *, int);


typedef int __io_close_fn(void *);

#line 46 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;

#line 62 "/usr/include/stdio.h"
typedef struct _IO_FILE __FILE;

#line 764 "/usr/include/stdlib.h"
typedef int (*__compar_fn_t)(const void *, const void *);

#line 49 "/usr/include/sys/select.h"
typedef long int suseconds_t;

#line 55 "/usr/include/sys/select.h"
typedef long int __fd_mask;

#line 85 "/usr/include/sys/select.h"
typedef long int fd_mask;

#line 35 "/usr/include/sys/types.h"
typedef unsigned char u_char;
typedef unsigned short int u_short;
typedef unsigned int u_int;
typedef unsigned long int u_long;

#line 50 "/usr/include/sys/types.h"
typedef unsigned long int ino_t;

#line 67 "/usr/include/sys/types.h"
typedef unsigned int gid_t;




typedef unsigned int mode_t;




typedef unsigned int nlink_t;




typedef unsigned int uid_t;

#line 88 "/usr/include/sys/types.h"
typedef long int off_t;

#line 100 "/usr/include/sys/types.h"
typedef int pid_t;




typedef unsigned int id_t;




typedef int ssize_t;

#line 116 "/usr/include/sys/types.h"
typedef int daddr_t;
typedef char *caddr_t;

#line 123 "/usr/include/sys/types.h"
typedef int key_t;

#line 151 "/usr/include/sys/types.h"
typedef unsigned long int ulong;
typedef unsigned short int ushort;
typedef unsigned int uint;

#line 163 "/usr/include/sys/types.h"
typedef char int8_t;
typedef short int int16_t;
typedef int int32_t;

#line 174 "/usr/include/sys/types.h"
typedef unsigned char u_int8_t;
typedef unsigned short int u_int16_t;
typedef unsigned int u_int32_t;

#line 183 "/usr/include/sys/types.h"
typedef int register_t;

#line 235 "/usr/include/sys/types.h"
typedef long int blkcnt_t;



typedef unsigned long int fsblkcnt_t;



typedef unsigned long int fsfilcnt_t;

#line 77 "/usr/include/time.h"
typedef long int time_t;

#line 93 "/usr/include/time.h"
typedef int clockid_t;

#line 105 "/usr/include/time.h"
typedef void *timer_t;

#line 43 "/usr/lib/gcc/i386-redhat-linux/3.4.6/include/stdarg.h"
typedef void *__gnuc_va_list;

#line 213 "/usr/lib/gcc/i386-redhat-linux/3.4.6/include/stddef.h"
typedef unsigned int size_t;

#line 354 "/usr/lib/gcc/i386-redhat-linux/3.4.6/include/stddef.h"
typedef unsigned int wint_t;

#line 50 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef unsigned long int pthread_t;

#line 70 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef struct __pthread_internal_slist __pthread_slist_t;

#line 143 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef unsigned int pthread_key_t;



typedef int pthread_once_t;

#line 204 "/usr/local/packages/sce-20100908/inc/bits/pthreadtypes.h"
typedef volatile int pthread_spinlock_t;

#line 57 "/usr/local/packages/sce-20100908/inc/sim/time.sh"
typedef unsigned long long int sim_time;

typedef unsigned long long int sim_delta;

typedef char sim_time_string[21];

#line 4 "OS.sc"
typedef int TASK;

#line 7 "c_int7220_queue_both_SR.sc"
typedef int int7220[7220];

#line 9 "c_uchar7220_queue_both_SR.sc"
typedef unsigned char uchar7220[7220];

#line 8 "susan.sh"
typedef int TOTAL_TYPE;

#line 21 "susan.sh"
typedef unsigned char uchar;

// class declarations ////////////////////////////////////////////////

#line 719 "susan_edge_detector.h"
class c_double_handshake_signal;
class IMasterHardwareBusProtocol;
class ISlaveHardwareBusProtocol;
class MasterHardwareBus;
class HardwareBusProtocolTLM;
class SlaveHardwareBus;
class IMasterHardwareBusLinkAccess;
class ISlaveHardwareBusLinkAccess;
class MasterHardwareBusLinkAccess;
class SlaveHardwareBusLinkAccess;
class IMasterHardwareBus;
class ISlaveHardwareBus;
class HardwareBus;
class OSAPI;
class OS;
class c_double_handshake;

#line 72 "c_double_handshake.sc"
/* note c_double_handshake._SCE_STANDARD_LIB = { "c_double_handshake" }; */

#line 740 "susan_edge_detector.h"
class c_handshake;

#line 56 "c_handshake.sc"
/* note c_handshake._SCE_STANDARD_LIB = { "c_handshake" }; */

#line 746 "susan_edge_detector.h"
class i_int7220_tranceiver;

#line 8 "c_int7220_queue_both_SR.sc"
/* note i_int7220_tranceiver._SCE_STANDARD_LIB = { "i_tranceiver","int7220","int7220" }; */

#line 752 "susan_edge_detector.h"
class i_int7220_sender;

#line 9 "c_int7220_queue_both_SR.sc"
/* note i_int7220_sender._SCE_STANDARD_LIB = { "i_sender","int7220","int7220" }; */

#line 758 "susan_edge_detector.h"
class i_int7220_receiver;

#line 10 "c_int7220_queue_both_SR.sc"
/* note i_int7220_receiver._SCE_STANDARD_LIB = { "i_receiver","int7220","int7220" }; */

#line 764 "susan_edge_detector.h"
class c_int7220_queue_R;

#line 11 "c_int7220_queue_both_SR.sc"
/* note c_int7220_queue_R._SCE_STANDARD_LIB = { "c_queue","int7220","int7220" }; */

#line 770 "susan_edge_detector.h"
class c_int7220_queue_S;

#line 11 "c_int7220_queue_both_SR.sc"
/* note c_int7220_queue_S._SCE_STANDARD_LIB = { "c_queue","int7220","int7220" }; */

#line 776 "susan_edge_detector.h"
class c_int7220_queue_both_SR;

#line 11 "c_int7220_queue_both_SR.sc"
/* note c_int7220_queue_both_SR._SCE_STANDARD_LIB = { "c_queue","int7220","int7220" }; */

#line 782 "susan_edge_detector.h"
class c_queue;

#line 77 "c_queue.sc"
/* note c_queue._SCE_STANDARD_LIB = { "c_queue" }; */

#line 788 "susan_edge_detector.h"
class i_uchar7220_tranceiver;

#line 10 "c_uchar7220_queue_both_SR.sc"
/* note i_uchar7220_tranceiver._SCE_STANDARD_LIB = { "i_tranceiver","uchar7220","uchar7220" }; */

#line 794 "susan_edge_detector.h"
class i_uchar7220_sender;

#line 11 "c_uchar7220_queue_both_SR.sc"
/* note i_uchar7220_sender._SCE_STANDARD_LIB = { "i_sender","uchar7220","uchar7220" }; */

#line 800 "susan_edge_detector.h"
class i_uchar7220_receiver;

#line 12 "c_uchar7220_queue_both_SR.sc"
/* note i_uchar7220_receiver._SCE_STANDARD_LIB = { "i_receiver","uchar7220","uchar7220" }; */

#line 806 "susan_edge_detector.h"
class c_uchar7220_queue_R;

#line 13 "c_uchar7220_queue_both_SR.sc"
/* note c_uchar7220_queue_R._SCE_STANDARD_LIB = { "c_queue","uchar7220","uchar7220" }; */

#line 812 "susan_edge_detector.h"
class c_uchar7220_queue_S;

#line 13 "c_uchar7220_queue_both_SR.sc"
/* note c_uchar7220_queue_S._SCE_STANDARD_LIB = { "c_queue","uchar7220","uchar7220" }; */

#line 818 "susan_edge_detector.h"
class c_uchar7220_queue_both_SR;

#line 13 "c_uchar7220_queue_both_SR.sc"
/* note c_uchar7220_queue_both_SR._SCE_STANDARD_LIB = { "c_queue","uchar7220","uchar7220" }; */

#line 824 "susan_edge_detector.h"
class Design;
class DetectEdges;
class Edges;
class EdgeDrawThread_PartA;
class EdgeDrawThread_PartB;
class EdgeDraw_ReadInput;
class EdgeDraw_WriteOutput;
class EdgeDraw_PartA;
class EdgeDraw_PartB;
class EdgeDraw;
class Draw;
class i_receive;

#line 29 "i_receive.sc"
/* note i_receive._SCE_STANDARD_LIB = { "i_receive" }; */

#line 841 "susan_edge_detector.h"
class i_receiver;

#line 25 "i_receiver.sc"
/* note i_receiver._SCE_STANDARD_LIB = { "i_receiver" }; */

#line 847 "susan_edge_detector.h"
class i_send;

#line 27 "i_send.sc"
/* note i_send._SCE_STANDARD_LIB = { "i_send" }; */

#line 853 "susan_edge_detector.h"
class i_sender;

#line 26 "i_sender.sc"
/* note i_sender._SCE_STANDARD_LIB = { "i_sender" }; */

#line 859 "susan_edge_detector.h"
class i_tranceiver;

#line 27 "i_tranceiver.sc"
/* note i_tranceiver._SCE_STANDARD_LIB = { "i_tranceiver" }; */

#line 865 "susan_edge_detector.h"
class master_send_driver;
class master_receive_driver;
class susan_driver_wrapper;
class Monitor;
class ReadImage;
class SetupBrightnessLutThread;
class SetupBrightnessLut;
class slave_send_driver;
class slave_receive_driver;
class readImage_driver_wrapper;
class writeImage_driver_wrapper;
class Stimulus;
class Susan;
class Main;
class SusanEdgesThread_PartA;
class SusanEdgesThread_PartB;
class SusanEdges_ReadInput;
class SusanEdges_WriteOutput;
class SusanEdges_PartA;
class SusanEdges_PartB;
class SusanEdges;
class SusanThinThread;
class SusanThin_ReadInput;
class SusanThin_WriteOutput;
class SusanThin;
class Thin;
class WriteImage;

// interface class definitions ///////////////////////////////////////

#line 33 "HWBus.sc"
class IMasterHardwareBusProtocol
{
private:
public:

#line 902 "susan_edge_detector.h"
    virtual ~IMasterHardwareBusProtocol(void){};

#line 36 "HWBus.sc"
    virtual void masterRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *) = 0;

#line 35 "HWBus.sc"
    virtual void masterWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>) = 0;
private:
};


class ISlaveHardwareBusProtocol
{
private:
public:

#line 919 "susan_edge_detector.h"
    virtual ~ISlaveHardwareBusProtocol(void){};

#line 43 "HWBus.sc"
    virtual void slaveRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *) = 0;

#line 42 "HWBus.sc"
    virtual void slaveWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>) = 0;
private:
};

#line 218 "HWBus.sc"
class IMasterHardwareBusLinkAccess
{
private:
public:

#line 936 "susan_edge_detector.h"
    virtual ~IMasterHardwareBusLinkAccess(void){};

#line 220 "HWBus.sc"
    virtual void MasterRead(int, void *, unsigned long int) = 0;
    virtual void MasterWrite(int, const void *, unsigned long int) = 0;
private:
};
class ISlaveHardwareBusLinkAccess
{
private:
public:

#line 949 "susan_edge_detector.h"
    virtual ~ISlaveHardwareBusLinkAccess(void){};

#line 226 "HWBus.sc"
    virtual void SlaveRead(int, void *, unsigned long int) = 0;
    virtual void SlaveWrite(int, const void *, unsigned long int) = 0;
private:
};

#line 381 "HWBus.sc"
class IMasterHardwareBus
{
private:
public:

#line 964 "susan_edge_detector.h"
    virtual ~IMasterHardwareBus(void){};

#line 383 "HWBus.sc"
    virtual void MasterRead(bit<_BITLEN(1,0),true>, void *, unsigned long int) = 0;


    virtual void MasterSyncReceive() = 0;
    virtual void MasterSyncReceive2() = 0;

#line 384 "HWBus.sc"
    virtual void MasterWrite(bit<_BITLEN(1,0),true>, const void *, unsigned long int) = 0;
private:
};




class ISlaveHardwareBus
{
private:
public:

#line 987 "susan_edge_detector.h"
    virtual ~ISlaveHardwareBus(void){};

#line 393 "HWBus.sc"
    virtual void SlaveRead(bit<_BITLEN(1,0),true>, void *, unsigned long int) = 0;


    virtual void SlaveSyncSend() = 0;
    virtual void SlaveSyncSend2() = 0;

#line 394 "HWBus.sc"
    virtual void SlaveWrite(bit<_BITLEN(1,0),true>, const void *, unsigned long int) = 0;
private:
};

#line 5 "OS.sc"
class OSAPI
{
private:
public:

#line 1008 "susan_edge_detector.h"
    virtual ~OSAPI(void){};

#line 25 "OS.sc"
    virtual void par_end(int) = 0;

#line 24 "OS.sc"
    virtual int par_start(void) = 0;

    virtual void post_wait(int) = 0;

#line 13 "OS.sc"
    virtual int pre_wait(void) = 0;



    virtual void printQueue(void) = 0;

#line 28 "OS.sc"
    virtual int schedule(void) = 0;

#line 16 "OS.sc"
    virtual void start(int) = 0;

#line 15 "OS.sc"
    virtual void task_activate(int) = 0;




    virtual void task_terminate() = 0;

#line 27 "OS.sc"
    virtual void time_wait(int) = 0;
private:
};

#line 8 "c_int7220_queue_both_SR.sc"
class i_int7220_tranceiver
{
private:
public:

#line 1051 "susan_edge_detector.h"
    virtual ~i_int7220_tranceiver(void){};

#line 8 "c_int7220_queue_both_SR.sc"
    virtual void receive(int (*)[7220]) = 0; virtual void send(int [7220]) = 0;
private:
};

#line 9 "c_int7220_queue_both_SR.sc"
class i_int7220_sender
{
private:
public:

#line 1065 "susan_edge_detector.h"
    virtual ~i_int7220_sender(void){};

#line 9 "c_int7220_queue_both_SR.sc"
    virtual void send(int [7220]) = 0;
private:
};

#line 10 "c_int7220_queue_both_SR.sc"
class i_int7220_receiver
{
private:
public:

#line 1079 "susan_edge_detector.h"
    virtual ~i_int7220_receiver(void){};

#line 10 "c_int7220_queue_both_SR.sc"
    virtual void receive(int (*)[7220]) = 0;
private:
};

#line 10 "c_uchar7220_queue_both_SR.sc"
class i_uchar7220_tranceiver
{
private:
public:

#line 1093 "susan_edge_detector.h"
    virtual ~i_uchar7220_tranceiver(void){};

#line 10 "c_uchar7220_queue_both_SR.sc"
    virtual void receive(unsigned char (*)[7220]) = 0; virtual void send(unsigned char [7220]) = 0;
private:
};

#line 11 "c_uchar7220_queue_both_SR.sc"
class i_uchar7220_sender
{
private:
public:

#line 1107 "susan_edge_detector.h"
    virtual ~i_uchar7220_sender(void){};

#line 11 "c_uchar7220_queue_both_SR.sc"
    virtual void send(unsigned char [7220]) = 0;
private:
};

#line 12 "c_uchar7220_queue_both_SR.sc"
class i_uchar7220_receiver
{
private:
public:

#line 1121 "susan_edge_detector.h"
    virtual ~i_uchar7220_receiver(void){};

#line 12 "c_uchar7220_queue_both_SR.sc"
    virtual void receive(unsigned char (*)[7220]) = 0;
private:
};

#line 27 "i_receive.sc"
class i_receive
{
private:
public:

#line 1135 "susan_edge_detector.h"
    virtual ~i_receive(void){};

#line 31 "i_receive.sc"
    virtual void receive(void) = 0;
private:
};

#line 23 "i_receiver.sc"
class i_receiver
{
private:
public:

#line 1149 "susan_edge_detector.h"
    virtual ~i_receiver(void){};

#line 27 "i_receiver.sc"
    virtual void receive(void *, unsigned long int) = 0;
private:
};

#line 25 "i_send.sc"
class i_send
{
private:
public:

#line 1163 "susan_edge_detector.h"
    virtual ~i_send(void){};

#line 29 "i_send.sc"
    virtual void send(void) = 0;
private:
};

#line 24 "i_sender.sc"
class i_sender
{
private:
public:

#line 1177 "susan_edge_detector.h"
    virtual ~i_sender(void){};

#line 28 "i_sender.sc"
    virtual void send(const void *, unsigned long int) = 0;
private:
};

#line 25 "i_tranceiver.sc"
class i_tranceiver
{
private:
public:

#line 1191 "susan_edge_detector.h"
    virtual ~i_tranceiver(void){};

#line 30 "i_tranceiver.sc"
    virtual void receive(void *, unsigned long int) = 0;

#line 29 "i_tranceiver.sc"
    virtual void send(const void *, unsigned long int) = 0;
private:
};

// behavior and channel class definitions ////////////////////////////

#line 6 "./c_double_handshake_signal.sc"
class c_double_handshake_signal : public _specc::channel, public i_send, public i_receive
{
private:
public:

#line 1210 "susan_edge_detector.h"
    c_double_handshake_signal();
    virtual ~c_double_handshake_signal(void);
    void receive(void);
    void send(void);
private:

#line 10 "./c_double_handshake_signal.sc"
    _specc::event ack;

#line 9 "./c_double_handshake_signal.sc"
    _specc::event req;

    bool v;
    bool w;
};

#line 47 "HWBus.sc"
class MasterHardwareBus : public _specc::channel, public IMasterHardwareBusProtocol
{
private:

#line 47 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > (&A);
    _specc::signal<bit<_BITLEN(31,0),true> > (&D);
    _specc::signal<bit<_BITLEN(0,0),true> > (&ready);
    _specc::signal<bit<_BITLEN(0,0),true> > (&ack);
public:

#line 1239 "susan_edge_detector.h"
    MasterHardwareBus(_specc::signal<bit<_BITLEN(1,0),true> > (&A), _specc::signal<bit<_BITLEN(31,0),true> > (&D), _specc::signal<bit<_BITLEN(0,0),true> > (&ready), _specc::signal<bit<_BITLEN(0,0),true> > (&ack));
    virtual ~MasterHardwareBus(void);
    void masterRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *);
    void masterWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>);
private:
};

#line 93 "HWBus.sc"
class HardwareBusProtocolTLM : public _specc::channel, public IMasterHardwareBusProtocol, public ISlaveHardwareBusProtocol
{
private:

#line 93 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > (&A); _specc::signal<bit<_BITLEN(31,0),true> > (&D); _specc::event (&TLMEvent1); _specc::event (&TLMEvent2);
public:

#line 1256 "susan_edge_detector.h"
    HardwareBusProtocolTLM(_specc::signal<bit<_BITLEN(1,0),true> > (&A), _specc::signal<bit<_BITLEN(31,0),true> > (&D), _specc::event (&TLMEvent1), _specc::event (&TLMEvent2));
    virtual ~HardwareBusProtocolTLM(void);
    void masterRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *);
    void masterWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>);
    void slaveRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *);
    void slaveWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>);
private:
};

#line 138 "HWBus.sc"
class SlaveHardwareBus : public _specc::channel, public ISlaveHardwareBusProtocol
{
private:

#line 138 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > (&A);
    _specc::signal<bit<_BITLEN(31,0),true> > (&D);
    _specc::signal<bit<_BITLEN(0,0),true> > (&ready);
    _specc::signal<bit<_BITLEN(0,0),true> > (&ack);
public:

#line 1278 "susan_edge_detector.h"
    SlaveHardwareBus(_specc::signal<bit<_BITLEN(1,0),true> > (&A), _specc::signal<bit<_BITLEN(31,0),true> > (&D), _specc::signal<bit<_BITLEN(0,0),true> > (&ready), _specc::signal<bit<_BITLEN(0,0),true> > (&ack));
    virtual ~SlaveHardwareBus(void);
    void slaveRead(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true> *);
    void slaveWrite(bit<_BITLEN(1,0),true>, bit<_BITLEN(31,0),true>);
private:
};

#line 230 "HWBus.sc"
class MasterHardwareBusLinkAccess : public _specc::channel, public IMasterHardwareBusLinkAccess
{
private:

#line 230 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > (&A); _specc::signal<unsigned char [7220]> (&D); _specc::event (&TLMEvent1); _specc::event (&TLMEvent2);
public:

#line 1295 "susan_edge_detector.h"
    MasterHardwareBusLinkAccess(_specc::signal<bit<_BITLEN(1,0),true> > (&A), _specc::signal<unsigned char [7220]> (&D), _specc::event (&TLMEvent1), _specc::event (&TLMEvent2));
    virtual ~MasterHardwareBusLinkAccess(void);
    void MasterRead(int, void *, unsigned long int);
    void MasterWrite(int, const void *, unsigned long int);
private:
};

#line 306 "HWBus.sc"
class SlaveHardwareBusLinkAccess : public _specc::channel, public ISlaveHardwareBusLinkAccess
{
private:

#line 306 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > (&A); _specc::signal<unsigned char [7220]> (&D); _specc::event (&TLMEvent1); _specc::event (&TLMEvent2);
public:

#line 1312 "susan_edge_detector.h"
    SlaveHardwareBusLinkAccess(_specc::signal<bit<_BITLEN(1,0),true> > (&A), _specc::signal<unsigned char [7220]> (&D), _specc::event (&TLMEvent1), _specc::event (&TLMEvent2));
    virtual ~SlaveHardwareBusLinkAccess(void);
    void SlaveRead(int, void *, unsigned long int);
    void SlaveWrite(int, const void *, unsigned long int);
private:
};

#line 70 "c_double_handshake.sc"
class c_double_handshake : public _specc::channel, public i_sender, public i_receiver, public i_tranceiver
{
private:
public:

#line 1326 "susan_edge_detector.h"
    c_double_handshake();
    virtual ~c_double_handshake(void);
    void receive(void *, unsigned long int);
    void send(const void *, unsigned long int);
private:

#line 75 "c_double_handshake.sc"
    _specc::event ack;

#line 74 "c_double_handshake.sc"
    _specc::event req;



    const void *tmpd;
    unsigned long int tmpl;

#line 76 "c_double_handshake.sc"
    bool v;
    bool w;
};

#line 403 "HWBus.sc"
class HardwareBus : public _specc::channel, public IMasterHardwareBus, public ISlaveHardwareBus
{
private:
public:

#line 1355 "susan_edge_detector.h"
    HardwareBus();
    virtual ~HardwareBus(void);
    void MasterRead(bit<_BITLEN(1,0),true>, void *, unsigned long int);
    void MasterSyncReceive();
    void MasterSyncReceive2();
    void MasterWrite(bit<_BITLEN(1,0),true>, const void *, unsigned long int);
    void SlaveRead(bit<_BITLEN(1,0),true>, void *, unsigned long int);
    void SlaveSyncSend();
    void SlaveSyncSend2();
    void SlaveWrite(bit<_BITLEN(1,0),true>, const void *, unsigned long int);
private:

#line 407 "HWBus.sc"
    _specc::signal<bit<_BITLEN(1,0),true> > A;
    _specc::signal<unsigned char [7220]> D;

#line 414 "HWBus.sc"
    _specc::event TLMEvent1;
    _specc::event TLMEvent2;

#line 413 "HWBus.sc"
    _specc::signal<bit<_BITLEN(0,0),true> > ack;

#line 419 "HWBus.sc"
    _specc::signal<bit<_BITLEN(0,0),true> > int0;
    _specc::signal<bit<_BITLEN(0,0),true> > int1;

#line 412 "HWBus.sc"
    _specc::signal<bit<_BITLEN(0,0),true> > ready;

#line 409 "HWBus.sc"
    _specc::signal<unsigned char *> tmp;

#line 448 "HWBus.sc"
    MasterHardwareBusLinkAccess MasterLink;
    SlaveHardwareBusLinkAccess SlaveLink;

#line 435 "HWBus.sc"
    c_double_handshake SlaveSync1;

#line 434 "HWBus.sc"
    c_double_handshake SlaveSync2;
};

#line 32 "OS.sc"
class OS : public _specc::channel, public OSAPI
{
private:
public:

#line 1406 "susan_edge_detector.h"
    OS();
    virtual ~OS(void);
    void dispatch(void);
    void increment_head();
    void increment_tail();
    void par_end(int);
    int par_start(void);
    int pop();
    void post_wait(int);
    int pre_wait(void);
    void printQueue(void);
    bool push(int);
    int schedule(void);
    void start(int);
    void task_activate(int);
    void task_terminate();
    void time_wait(int);
    void trigger_event(int);
    void wait_event(int);
    void yield();
private:

#line 50 "OS.sc"
    int QueueEmpty;

#line 49 "OS.sc"
    int QueueFull;

#line 41 "OS.sc"
    int current;
    _specc::event e1;
    _specc::event e2;
    _specc::event e3;
    _specc::event e4;

    int head;

#line 34 "OS.sc"
    const int master;




    const int nullTask;

#line 46 "OS.sc"
    int readyQueue[40];

    int tail;

#line 35 "OS.sc"
    const int task1;
    const int task2;
    const int task3;
    const int task4;
};

#line 54 "c_handshake.sc"
class c_handshake : public _specc::channel, public i_send, public i_receive
{
private:
public:

#line 1470 "susan_edge_detector.h"
    c_handshake();
    virtual ~c_handshake(void);
    void receive(void);
    void send(void);
private:

#line 58 "c_handshake.sc"
    _specc::event e;
    bool f;
    bool w;
};

#line 11 "c_int7220_queue_both_SR.sc"
class c_int7220_queue_R : public _specc::channel, public i_int7220_sender, public i_int7220_receiver, public i_int7220_tranceiver
{
private:

#line 11 "c_int7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1492 "susan_edge_detector.h"
    c_int7220_queue_R(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_int7220_queue_R(void);
    void cleanup(void);
    void receive(int (*)[7220]);
    void send(int [7220]);
    void setup(void);
private:

#line 11 "c_int7220_queue_both_SR.sc"
    int (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws;
};

#line 11 "c_int7220_queue_both_SR.sc"
class c_int7220_queue_S : public _specc::channel, public i_int7220_sender, public i_int7220_receiver, public i_int7220_tranceiver
{
private:

#line 11 "c_int7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1514 "susan_edge_detector.h"
    c_int7220_queue_S(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_int7220_queue_S(void);
    void cleanup(void);
    void receive(int (*)[7220]);
    void send(int [7220]);
    void setup(void);
private:

#line 11 "c_int7220_queue_both_SR.sc"
    int (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws;
};

#line 11 "c_int7220_queue_both_SR.sc"
class c_int7220_queue_both_SR : public _specc::channel, public i_int7220_sender, public i_int7220_receiver, public i_int7220_tranceiver
{
private:

#line 11 "c_int7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1536 "susan_edge_detector.h"
    c_int7220_queue_both_SR(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_int7220_queue_both_SR(void);
    void cleanup(void);
    void receive(int (*)[7220]);
    void send(int [7220]);
    void setup(void);
private:

#line 11 "c_int7220_queue_both_SR.sc"
    int (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws; int x;
};

#line 74 "c_queue.sc"
class c_queue : public _specc::channel, public i_sender, public i_receiver, public i_tranceiver
{
private:

#line 74 "c_queue.sc"
    const unsigned long int (&size);
public:

#line 1558 "susan_edge_detector.h"
    c_queue(const unsigned long int (&size));
    virtual ~c_queue(void);
    void cleanup(void);
    void receive(void *, unsigned long int);
    void send(const void *, unsigned long int);
    void setup(void);
private:

#line 85 "c_queue.sc"
    char *buffer;

#line 84 "c_queue.sc"
    unsigned long int n;

#line 83 "c_queue.sc"
    unsigned long int p;

#line 79 "c_queue.sc"
    _specc::event r;
    _specc::event s;
    unsigned long int wr;
    unsigned long int ws;
};

#line 13 "c_uchar7220_queue_both_SR.sc"
class c_uchar7220_queue_R : public _specc::channel, public i_uchar7220_sender, public i_uchar7220_receiver, public i_uchar7220_tranceiver
{
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1592 "susan_edge_detector.h"
    c_uchar7220_queue_R(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_uchar7220_queue_R(void);
    void cleanup(void);
    void receive(unsigned char (*)[7220]);
    void send(unsigned char [7220]);
    void setup(void);
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    unsigned char (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws;
};

#line 13 "c_uchar7220_queue_both_SR.sc"
class c_uchar7220_queue_S : public _specc::channel, public i_uchar7220_sender, public i_uchar7220_receiver, public i_uchar7220_tranceiver
{
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1614 "susan_edge_detector.h"
    c_uchar7220_queue_S(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_uchar7220_queue_S(void);
    void cleanup(void);
    void receive(unsigned char (*)[7220]);
    void send(unsigned char [7220]);
    void setup(void);
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    unsigned char (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws;
};

#line 13 "c_uchar7220_queue_both_SR.sc"
class c_uchar7220_queue_both_SR : public _specc::channel, public i_uchar7220_sender, public i_uchar7220_receiver, public i_uchar7220_tranceiver
{
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    const unsigned long int (&size); OSAPI (&myOS);
public:

#line 1636 "susan_edge_detector.h"
    c_uchar7220_queue_both_SR(const unsigned long int (&size), OSAPI (&myOS));
    virtual ~c_uchar7220_queue_both_SR(void);
    void cleanup(void);
    void receive(unsigned char (*)[7220]);
    void send(unsigned char [7220]);
    void setup(void);
private:

#line 13 "c_uchar7220_queue_both_SR.sc"
    unsigned char (*buffer)[7220]; unsigned long int n; unsigned long int p; _specc::event r; _specc::event s; int t; unsigned long int wr; unsigned long int ws; int x;
};

#line 7 "master_driver.sc"
class master_send_driver : public _specc::channel, public i_uchar7220_sender
{
private:

#line 7 "master_driver.sc"
    IMasterHardwareBus (&myHardwareBus); bit<_BITLEN(1,0),true> (&addr);
public:

#line 1658 "susan_edge_detector.h"
    master_send_driver(IMasterHardwareBus (&myHardwareBus), bit<_BITLEN(1,0),true> (&addr));
    virtual ~master_send_driver(void);
    void send(unsigned char [7220]);
private:

#line 8 "master_driver.sc"
    unsigned long int mySize;
};

#line 18 "master_driver.sc"
class master_receive_driver : public _specc::channel, public i_uchar7220_receiver
{
private:

#line 18 "master_driver.sc"
    IMasterHardwareBus (&myHardwareBus); bit<_BITLEN(1,0),true> (&addr);
public:

#line 1677 "susan_edge_detector.h"
    master_receive_driver(IMasterHardwareBus (&myHardwareBus), bit<_BITLEN(1,0),true> (&addr));
    virtual ~master_receive_driver(void);
    void receive(unsigned char (*)[7220]);
private:

#line 19 "master_driver.sc"
    unsigned long int mySize;
};

#line 3 "setup_brightness_lut.sc"
class SetupBrightnessLutThread : public _specc::behavior
{
private:

#line 3 "setup_brightness_lut.sc"
    unsigned char (&bp)[516]; int (&thID); OSAPI (&myOS);
public:

#line 1696 "susan_edge_detector.h"
    SetupBrightnessLutThread(unsigned int _idcnt, unsigned char (&bp)[516], int (&thID), OSAPI (&myOS));
    virtual ~SetupBrightnessLutThread(void);
    void main(void);
private:
};

#line 27 "setup_brightness_lut.sc"
class SetupBrightnessLut : public _specc::behavior
{
private:

#line 27 "setup_brightness_lut.sc"
    unsigned char (&bp)[516]; OSAPI (&myOS);
public:

#line 1712 "susan_edge_detector.h"
    SetupBrightnessLut(unsigned int _idcnt, unsigned char (&bp)[516], OSAPI (&myOS));
    virtual ~SetupBrightnessLut(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 30 "setup_brightness_lut.sc"
    SetupBrightnessLutThread setup_brightness_thread_0;
    SetupBrightnessLutThread setup_brightness_thread_1;
};

#line 267 "susan_edges.sc"
class SusanEdges_ReadInput : public _specc::behavior
{
private:

#line 267 "susan_edges.sc"
    i_uchar7220_receiver (&in_image); unsigned char (&in_image_buffer)[7220]; int (&r)[7220]; unsigned char (&mid)[7220]; OSAPI (&myOS);
public:

#line 1734 "susan_edge_detector.h"
    SusanEdges_ReadInput(unsigned int _idcnt, i_uchar7220_receiver (&in_image), unsigned char (&in_image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], OSAPI (&myOS));
    virtual ~SusanEdges_ReadInput(void);
    void main(void);
private:
};

#line 281 "susan_edges.sc"
class SusanEdges_WriteOutput : public _specc::behavior
{
private:

#line 281 "susan_edges.sc"
    i_int7220_sender (&out_r); i_uchar7220_sender (&out_mid);
    i_uchar7220_sender (&out_image); int (&r)[7220];
    unsigned char (&mid)[7220]; unsigned char (&out_image_buffer)[7220];
public:

#line 1752 "susan_edge_detector.h"
    SusanEdges_WriteOutput(unsigned int _idcnt, i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&out_image_buffer)[7220]);
    virtual ~SusanEdges_WriteOutput(void);
    void main(void);
private:
};

#line 5 "susan_edges.sc"
class SusanEdgesThread_PartA : public _specc::behavior
{
private:

#line 5 "susan_edges.sc"
    unsigned char (&image_buffer)[7220]; int (&r)[7220]; unsigned char (&bp)[516]; int (&thID); OSAPI (&myOS);
public:

#line 1768 "susan_edge_detector.h"
    SusanEdgesThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&myOS));
    virtual ~SusanEdgesThread_PartA(void);
    void main(void);
private:
};

#line 297 "susan_edges.sc"
class SusanEdges_PartA : public _specc::behavior
{
private:

#line 297 "susan_edges.sc"
    unsigned char (&image_buffer)[7220]; int (&r)[7220]; unsigned char (&bp)[516]; OSAPI (&myOS);
public:

#line 1784 "susan_edge_detector.h"
    SusanEdges_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], OSAPI (&myOS));
    virtual ~SusanEdges_PartA(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 299 "susan_edges.sc"
    SusanEdgesThread_PartA susan_edges_a_thread_0;
    SusanEdgesThread_PartA susan_edges_a_thread_1;
};

#line 84 "susan_edges.sc"
class SusanEdgesThread_PartB : public _specc::behavior
{
private:

#line 84 "susan_edges.sc"
    unsigned char (&image_buffer)[7220]; int (&r)[7220]; unsigned char (&mid)[7220]; unsigned char (&bp)[516]; int (&thID); OSAPI (&myOS);
public:

#line 1806 "susan_edge_detector.h"
    SusanEdgesThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&myOS));
    virtual ~SusanEdgesThread_PartB(void);
    void main(void);
private:
};

#line 309 "susan_edges.sc"
class SusanEdges_PartB : public _specc::behavior
{
private:

#line 309 "susan_edges.sc"
    unsigned char (&image_buffer)[7220]; int (&r)[7220]; unsigned char (&mid)[7220]; unsigned char (&bp)[516]; OSAPI (&myOS);
public:

#line 1822 "susan_edge_detector.h"
    SusanEdges_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], OSAPI (&myOS));
    virtual ~SusanEdges_PartB(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 311 "susan_edges.sc"
    SusanEdgesThread_PartB susan_edges_b_thread_0;
    SusanEdgesThread_PartB susan_edges_b_thread_1;
};

#line 321 "susan_edges.sc"
class SusanEdges : public _specc::behavior
{
private:

#line 321 "susan_edges.sc"
    i_uchar7220_receiver (&in_image); i_int7220_sender (&out_r); i_uchar7220_sender (&out_mid); unsigned char (&bp)[516]; i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 1844 "susan_edge_detector.h"
    SusanEdges(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), unsigned char (&bp)[516], i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~SusanEdges(void);
    void main(void);
private:

#line 324 "susan_edges.sc"
    unsigned char image_buffer[7220];

    unsigned char mid[7220];

#line 325 "susan_edges.sc"
    int r[7220];




    SusanEdges_PartA susan_edges_a;
    SusanEdges_PartB susan_edges_b;

#line 328 "susan_edges.sc"
    SusanEdges_ReadInput susan_edges_read_input;
    SusanEdges_WriteOutput susan_edges_write_output;
};

#line 6 "detect_edges.sc"
class DetectEdges : public _specc::behavior
{
private:

#line 6 "detect_edges.sc"
    i_uchar7220_receiver (&in_image); i_int7220_sender (&out_r); i_uchar7220_sender (&out_mid); i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 1878 "susan_edge_detector.h"
    DetectEdges(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~DetectEdges(void);
    void main(void);
private:

#line 9 "detect_edges.sc"
    unsigned char bp[516];

    SetupBrightnessLut setup_brightness_lut;
    SusanEdges susan_edges;
};

#line 26 "detect_edges.sc"
class Edges : public _specc::behavior
{
private:

#line 26 "detect_edges.sc"
    i_uchar7220_receiver (&in_image); i_int7220_sender (&out_r); i_uchar7220_sender (&out_mid); i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 1900 "susan_edge_detector.h"
    Edges(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~Edges(void);
    void main(void);
private:

#line 30 "detect_edges.sc"
    DetectEdges detect_edges;
};

#line 65 "edge_draw.sc"
class EdgeDraw_ReadInput : public _specc::behavior
{
private:

#line 65 "edge_draw.sc"
    i_uchar7220_receiver (&in_image); i_uchar7220_receiver (&in_mid); unsigned char (&image_buffer)[7220]; unsigned char (&mid)[7220]; OSAPI (&myOS);
public:

#line 1919 "susan_edge_detector.h"
    EdgeDraw_ReadInput(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&myOS));
    virtual ~EdgeDraw_ReadInput(void);
    void main(void);
private:
};

#line 73 "edge_draw.sc"
class EdgeDraw_WriteOutput : public _specc::behavior
{
private:

#line 73 "edge_draw.sc"
    unsigned char (&image_buffer)[7220]; i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 1935 "susan_edge_detector.h"
    EdgeDraw_WriteOutput(unsigned int _idcnt, unsigned char (&image_buffer)[7220], i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~EdgeDraw_WriteOutput(void);
    void main(void);
private:
};

#line 5 "edge_draw.sc"
class EdgeDrawThread_PartA : public _specc::behavior
{
private:

#line 5 "edge_draw.sc"
    unsigned char (&image_buffer)[7220]; unsigned char (&mid)[7220]; int (&thID); OSAPI (&myOS);
public:

#line 1951 "susan_edge_detector.h"
    EdgeDrawThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&myOS));
    virtual ~EdgeDrawThread_PartA(void);
    void main(void);
private:
};

#line 84 "edge_draw.sc"
class EdgeDraw_PartA : public _specc::behavior
{
private:

#line 84 "edge_draw.sc"
    unsigned char (&image_buffer)[7220]; unsigned char (&mid)[7220]; OSAPI (&myOS);
public:

#line 1967 "susan_edge_detector.h"
    EdgeDraw_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&myOS));
    virtual ~EdgeDraw_PartA(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 87 "edge_draw.sc"
    EdgeDrawThread_PartA edge_draw_a_thread_0;
    EdgeDrawThread_PartA edge_draw_a_thread_1;
};

#line 38 "edge_draw.sc"
class EdgeDrawThread_PartB : public _specc::behavior
{
private:

#line 38 "edge_draw.sc"
    unsigned char (&image_buffer)[7220]; unsigned char (&mid)[7220]; int (&thID); OSAPI (&myOS);
public:

#line 1989 "susan_edge_detector.h"
    EdgeDrawThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&myOS));
    virtual ~EdgeDrawThread_PartB(void);
    void main(void);
private:
};

#line 97 "edge_draw.sc"
class EdgeDraw_PartB : public _specc::behavior
{
private:

#line 97 "edge_draw.sc"
    unsigned char (&image_buffer)[7220]; unsigned char (&mid)[7220]; OSAPI (&myOS);
public:

#line 2005 "susan_edge_detector.h"
    EdgeDraw_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&myOS));
    virtual ~EdgeDraw_PartB(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 100 "edge_draw.sc"
    EdgeDrawThread_PartB edge_draw_b_thread_0;
    EdgeDrawThread_PartB edge_draw_b_thread_1;
};

#line 111 "edge_draw.sc"
class EdgeDraw : public _specc::behavior
{
private:

#line 111 "edge_draw.sc"
    i_uchar7220_receiver (&in_image); i_uchar7220_receiver (&in_mid); i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 2027 "susan_edge_detector.h"
    EdgeDraw(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~EdgeDraw(void);
    void main(void);
private:

#line 115 "edge_draw.sc"
    unsigned char image_buffer[7220];
    unsigned char mid[7220];



    EdgeDraw_PartA edge_draw_a;
    EdgeDraw_PartB edge_draw_b;

#line 118 "edge_draw.sc"
    EdgeDraw_ReadInput edge_draw_read_input;
    EdgeDraw_WriteOutput edge_draw_write_output;
};

#line 137 "edge_draw.sc"
class Draw : public _specc::behavior
{
private:

#line 137 "edge_draw.sc"
    i_uchar7220_receiver (&in_image); i_uchar7220_receiver (&in_mid); i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 2056 "susan_edge_detector.h"
    Draw(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~Draw(void);
    void main(void);
private:

#line 140 "edge_draw.sc"
    EdgeDraw edge_draw;
};

#line 206 "susan_thin.sc"
class SusanThin_ReadInput : public _specc::behavior
{
private:

#line 206 "susan_thin.sc"
    i_int7220_receiver (&in_r); i_uchar7220_receiver (&in_mid); int (&r)[7220]; unsigned char (&mid)[7220];
public:

#line 2075 "susan_edge_detector.h"
    SusanThin_ReadInput(unsigned int _idcnt, i_int7220_receiver (&in_r), i_uchar7220_receiver (&in_mid), int (&r)[7220], unsigned char (&mid)[7220]);
    virtual ~SusanThin_ReadInput(void);
    void main(void);
private:
};

#line 215 "susan_thin.sc"
class SusanThin_WriteOutput : public _specc::behavior
{
private:

#line 215 "susan_thin.sc"
    i_uchar7220_sender (&out_mid); unsigned char (&mid)[7220];
public:

#line 2091 "susan_edge_detector.h"
    SusanThin_WriteOutput(unsigned int _idcnt, i_uchar7220_sender (&out_mid), unsigned char (&mid)[7220]);
    virtual ~SusanThin_WriteOutput(void);
    void main(void);
private:
};

#line 5 "susan_thin.sc"
class SusanThinThread : public _specc::behavior
{
private:

#line 5 "susan_thin.sc"
    int (&r)[7220]; unsigned char (&mid)[7220]; int (&thID); OSAPI (&myOS);
public:

#line 2107 "susan_edge_detector.h"
    SusanThinThread(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&myOS));
    virtual ~SusanThinThread(void);
    void main(void);
private:
};

#line 224 "susan_thin.sc"
class SusanThin : public _specc::behavior
{
private:

#line 224 "susan_thin.sc"
    int (&r)[7220]; unsigned char (&mid)[7220]; OSAPI (&myOS);
public:

#line 2123 "susan_edge_detector.h"
    SusanThin(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], OSAPI (&myOS));
    virtual ~SusanThin(void);
    void main(void);
private:
    int _scc_const_port_0;
    int _scc_const_port_1;

#line 227 "susan_thin.sc"
    SusanThinThread susan_thin_thread_0;
    SusanThinThread susan_thin_thread_1;
};

#line 239 "susan_thin.sc"
class Thin : public _specc::behavior
{
private:

#line 239 "susan_thin.sc"
    i_int7220_receiver (&in_r); i_uchar7220_receiver (&in_mid); i_uchar7220_sender (&out_mid); OSAPI (&myOS);
public:

#line 2145 "susan_edge_detector.h"
    Thin(unsigned int _idcnt, i_int7220_receiver (&in_r), i_uchar7220_receiver (&in_mid), i_uchar7220_sender (&out_mid), OSAPI (&myOS));
    virtual ~Thin(void);
    void main(void);
private:

#line 243 "susan_thin.sc"
    unsigned char mid[7220];

#line 242 "susan_thin.sc"
    int r[7220];




    SusanThin susan_thin;

#line 245 "susan_thin.sc"
    SusanThin_ReadInput susan_thin_read_input;
    SusanThin_WriteOutput susan_thin_write_output;
};

#line 10 "susan.sc"
class Susan : public _specc::behavior
{
private:

#line 10 "susan.sc"
    i_uchar7220_receiver (&in_image); i_uchar7220_sender (&out_image); OSAPI (&myOS);
public:

#line 2176 "susan_edge_detector.h"
    Susan(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_sender (&out_image), OSAPI (&myOS));
    virtual ~Susan(void);
    void main(void);
private:
    unsigned long int _scc_const_port_0;
    unsigned long int _scc_const_port_1;
    unsigned long int _scc_const_port_2;
    unsigned long int _scc_const_port_3;

#line 20 "susan.sc"
    Draw draw;

#line 18 "susan.sc"
    Edges edges;

#line 17 "susan.sc"
    c_uchar7220_queue_both_SR image_edge_draw;

#line 16 "susan.sc"
    c_uchar7220_queue_both_SR mid;

#line 15 "susan.sc"
    c_uchar7220_queue_both_SR mid_edge_draw;

#line 14 "susan.sc"
    c_int7220_queue_both_SR r;




    Thin thin;
};

#line 28 "master_driver.sc"
class susan_driver_wrapper : public _specc::behavior
{
private:

#line 28 "master_driver.sc"
    IMasterHardwareBus (&myHardwareBus);
public:

#line 2219 "susan_edge_detector.h"
    susan_driver_wrapper(unsigned int _idcnt, IMasterHardwareBus (&myHardwareBus));
    virtual ~susan_driver_wrapper(void);
    void main(void);
private:

#line 34 "master_driver.sc"
    bit<_BITLEN(1,0),true> addr1;
    bit<_BITLEN(1,0),true> addr2;


    Susan TASK_PE1;

#line 36 "master_driver.sc"
    master_receive_driver myMaster_receive_driver;
    master_send_driver myMaster_send_driver;

#line 30 "master_driver.sc"
    OS myOS;
};

#line 6 "read_image.sc"
class ReadImage : public _specc::behavior
{
private:

#line 6 "read_image.sc"
    i_receive (&start); unsigned char (&image_buffer)[7220]; i_uchar7220_sender (&out_image);
public:

#line 2249 "susan_edge_detector.h"
    ReadImage(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_uchar7220_sender (&out_image));
    virtual ~ReadImage(void);
    void main(void);
private:
};

#line 7 "slave_driver.sc"
class slave_send_driver : public _specc::channel, public i_uchar7220_sender
{
private:

#line 7 "slave_driver.sc"
    ISlaveHardwareBus (&myHardwareBus); bit<_BITLEN(1,0),true> (&addr);
public:

#line 2265 "susan_edge_detector.h"
    slave_send_driver(ISlaveHardwareBus (&myHardwareBus), bit<_BITLEN(1,0),true> (&addr));
    virtual ~slave_send_driver(void);
    void send(unsigned char [7220]);
private:

#line 8 "slave_driver.sc"
    unsigned long int mySize;
};

#line 26 "slave_driver.sc"
class readImage_driver_wrapper : public _specc::behavior
{
private:

#line 26 "slave_driver.sc"
    ISlaveHardwareBus (&myHardwareBus); unsigned char (&image_buffer)[7220]; i_receive (&start);
public:

#line 2284 "susan_edge_detector.h"
    readImage_driver_wrapper(unsigned int _idcnt, ISlaveHardwareBus (&myHardwareBus), unsigned char (&image_buffer)[7220], i_receive (&start));
    virtual ~readImage_driver_wrapper(void);
    void main(void);
private:

#line 28 "slave_driver.sc"
    bit<_BITLEN(1,0),true> addr;

    ReadImage myRead_image;

#line 29 "slave_driver.sc"
    slave_send_driver mySlave_send_driver;
};

#line 16 "slave_driver.sc"
class slave_receive_driver : public _specc::channel, public i_uchar7220_receiver
{
private:

#line 16 "slave_driver.sc"
    ISlaveHardwareBus (&myHardwareBus); bit<_BITLEN(1,0),true> (&addr);
public:

#line 2308 "susan_edge_detector.h"
    slave_receive_driver(ISlaveHardwareBus (&myHardwareBus), bit<_BITLEN(1,0),true> (&addr));
    virtual ~slave_receive_driver(void);
    void receive(unsigned char (*)[7220]);
private:

#line 17 "slave_driver.sc"
    unsigned long int mySize;
};

#line 6 "write_image.sc"
class WriteImage : public _specc::behavior
{
private:

#line 6 "write_image.sc"
    i_uchar7220_receiver (&in_image); i_sender (&out_image);
public:

#line 2327 "susan_edge_detector.h"
    WriteImage(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_sender (&out_image));
    virtual ~WriteImage(void);
    void main(void);
private:
};

#line 43 "slave_driver.sc"
class writeImage_driver_wrapper : public _specc::behavior
{
private:

#line 43 "slave_driver.sc"
    ISlaveHardwareBus (&myHardwareBus); i_sender (&out_image_susan);
public:

#line 2343 "susan_edge_detector.h"
    writeImage_driver_wrapper(unsigned int _idcnt, ISlaveHardwareBus (&myHardwareBus), i_sender (&out_image_susan));
    virtual ~writeImage_driver_wrapper(void);
    void main(void);
private:

#line 46 "slave_driver.sc"
    bit<_BITLEN(1,0),true> addr;
    slave_receive_driver mySlave_receive_driver;
    WriteImage myWrite_image;
};

#line 14 "design.sc"
class Design : public _specc::behavior
{
private:

#line 14 "design.sc"
    i_receive (&start); unsigned char (&image_buffer)[7220]; i_sender (&out_image_susan);
public:

#line 2364 "susan_edge_detector.h"
    Design(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&out_image_susan));
    virtual ~Design(void);
    void main(void);
private:

#line 16 "design.sc"
    HardwareBus myHardwareBus;

    readImage_driver_wrapper myRead_image_driver;

#line 17 "design.sc"
    susan_driver_wrapper mySusan_driver_wrapper;

    writeImage_driver_wrapper myWrite_image_driver;
};

#line 7 "monitor.sc"
class Monitor : public _specc::behavior
{
private:

#line 7 "monitor.sc"
    i_receiver (&img); i_receiver (&start_time_channel);
public:

#line 2390 "susan_edge_detector.h"
    Monitor(unsigned int _idcnt, i_receiver (&img), i_receiver (&start_time_channel));
    virtual ~Monitor(void);
    void main(void);
private:
};

#line 9 "stimulus.sc"
class Stimulus : public _specc::behavior
{
private:

#line 9 "stimulus.sc"
    i_send (&start); unsigned char (&image_buffer)[7220]; i_sender (&start_time_channel);
public:

#line 2406 "susan_edge_detector.h"
    Stimulus(unsigned int _idcnt, i_send (&start), unsigned char (&image_buffer)[7220], i_sender (&start_time_channel));
    virtual ~Stimulus(void);
    void get_image(char [200], unsigned char *);
    int getint(struct _IO_FILE *);
    void main(void);
private:
};

#line 11 "susan_edge_detector.sc"
class Main : public _specc::class_type
{
private:
public:

#line 2421 "susan_edge_detector.h"
    Main(unsigned int _idcnt);
    virtual ~Main(void);
    int main(void);
private:

#line 14 "susan_edge_detector.sc"
    unsigned char image_buffer[7220];
    unsigned long int _scc_const_port_0;



    Design design;
    Monitor monitor;

#line 16 "susan_edge_detector.sc"
    c_double_handshake out_image;

#line 15 "susan_edge_detector.sc"
    c_double_handshake_signal start;

#line 13 "susan_edge_detector.sc"
    c_queue start_time;




    Stimulus stimulus;
};

// variable and function declarations ////////////////////////////////

#line 33 "/usr/include/alloca.h"
extern "C" void *alloca(unsigned int);

#line 55 "/usr/include/bits/mathcalls.h"
extern "C" double __acos(double); extern "C" float __acosf(float); extern "C" long double __acosl(long double); extern "C" double acos(double); extern "C" float acosf(float); extern "C" long double acosl(long double);

extern "C" double __asin(double); extern "C" float __asinf(float); extern "C" long double __asinl(long double); extern "C" double asin(double); extern "C" float asinf(float); extern "C" long double asinl(long double);

extern "C" double __atan(double); extern "C" float __atanf(float); extern "C" long double __atanl(long double); extern "C" double atan(double); extern "C" float atanf(float); extern "C" long double atanl(long double);

extern "C" double __atan2(double, double); extern "C" float __atan2f(float, float); extern "C" long double __atan2l(long double, long double); extern "C" double atan2(double, double); extern "C" float atan2f(float, float); extern "C" long double atan2l(long double, long double);


extern "C" double __cos(double); extern "C" float __cosf(float); extern "C" long double __cosl(long double); extern "C" double cos(double); extern "C" float cosf(float); extern "C" long double cosl(long double);

extern "C" double __sin(double); extern "C" float __sinf(float); extern "C" long double __sinl(long double); extern "C" double sin(double); extern "C" float sinf(float); extern "C" long double sinl(long double);

extern "C" double __tan(double); extern "C" float __tanf(float); extern "C" long double __tanl(long double); extern "C" double tan(double); extern "C" float tanf(float); extern "C" long double tanl(long double);




extern "C" double __cosh(double); extern "C" float __coshf(float); extern "C" long double __coshl(long double); extern "C" double cosh(double); extern "C" float coshf(float); extern "C" long double coshl(long double);

extern "C" double __sinh(double); extern "C" float __sinhf(float); extern "C" long double __sinhl(long double); extern "C" double sinh(double); extern "C" float sinhf(float); extern "C" long double sinhl(long double);

extern "C" double __tanh(double); extern "C" float __tanhf(float); extern "C" long double __tanhl(long double); extern "C" double tanh(double); extern "C" float tanhf(float); extern "C" long double tanhl(long double);

#line 89 "/usr/include/bits/mathcalls.h"
extern "C" double __acosh(double); extern "C" float __acoshf(float); extern "C" long double __acoshl(long double); extern "C" double acosh(double); extern "C" float acoshf(float); extern "C" long double acoshl(long double);

extern "C" double __asinh(double); extern "C" float __asinhf(float); extern "C" long double __asinhl(long double); extern "C" double asinh(double); extern "C" float asinhf(float); extern "C" long double asinhl(long double);

extern "C" double __atanh(double); extern "C" float __atanhf(float); extern "C" long double __atanhl(long double); extern "C" double atanh(double); extern "C" float atanhf(float); extern "C" long double atanhl(long double);

#line 101 "/usr/include/bits/mathcalls.h"
extern "C" double __exp(double); extern "C" float __expf(float); extern "C" long double __expl(long double); extern "C" double exp(double); extern "C" float expf(float); extern "C" long double expl(long double);


extern "C" double __frexp(double, int *); extern "C" float __frexpf(float, int *); extern "C" long double __frexpl(long double, int *); extern "C" double frexp(double, int *); extern "C" float frexpf(float, int *); extern "C" long double frexpl(long double, int *);


extern "C" double __ldexp(double, int); extern "C" float __ldexpf(float, int); extern "C" long double __ldexpl(long double, int); extern "C" double ldexp(double, int); extern "C" float ldexpf(float, int); extern "C" long double ldexpl(long double, int);


extern "C" double __log(double); extern "C" float __logf(float); extern "C" long double __logl(long double); extern "C" double log(double); extern "C" float logf(float); extern "C" long double logl(long double);


extern "C" double __log10(double); extern "C" float __log10f(float); extern "C" long double __log10l(long double); extern "C" double log10(double); extern "C" float log10f(float); extern "C" long double log10l(long double);


extern "C" double __modf(double, double *); extern "C" float __modff(float, float *); extern "C" long double __modfl(long double, long double *); extern "C" double modf(double, double *); extern "C" float modff(float, float *); extern "C" long double modfl(long double, long double *);

#line 129 "/usr/include/bits/mathcalls.h"
extern "C" double __expm1(double); extern "C" float __expm1f(float); extern "C" long double __expm1l(long double); extern "C" double expm1(double); extern "C" float expm1f(float); extern "C" long double expm1l(long double);


extern "C" double __log1p(double); extern "C" float __log1pf(float); extern "C" long double __log1pl(long double); extern "C" double log1p(double); extern "C" float log1pf(float); extern "C" long double log1pl(long double);


extern "C" double __logb(double); extern "C" float __logbf(float); extern "C" long double __logbl(long double); extern "C" double logb(double); extern "C" float logbf(float); extern "C" long double logbl(long double);

#line 154 "/usr/include/bits/mathcalls.h"
extern "C" double __pow(double, double); extern "C" float __powf(float, float); extern "C" long double __powl(long double, long double); extern "C" double pow(double, double); extern "C" float powf(float, float); extern "C" long double powl(long double, long double);


extern "C" double __sqrt(double); extern "C" float __sqrtf(float); extern "C" long double __sqrtl(long double); extern "C" double sqrt(double); extern "C" float sqrtf(float); extern "C" long double sqrtl(long double);

#line 163 "/usr/include/bits/mathcalls.h"
extern "C" double __hypot(double, double); extern "C" float __hypotf(float, float); extern "C" long double __hypotl(long double, long double); extern "C" double hypot(double, double); extern "C" float hypotf(float, float); extern "C" long double hypotl(long double, long double);

#line 170 "/usr/include/bits/mathcalls.h"
extern "C" double __cbrt(double); extern "C" float __cbrtf(float); extern "C" long double __cbrtl(long double); extern "C" double cbrt(double); extern "C" float cbrtf(float); extern "C" long double cbrtl(long double);

#line 179 "/usr/include/bits/mathcalls.h"
extern "C" double __ceil(double); extern "C" float __ceilf(float); extern "C" long double __ceill(long double); extern "C" double ceil(double); extern "C" float ceilf(float); extern "C" long double ceill(long double);


extern "C" double __fabs(double); extern "C" float __fabsf(float); extern "C" long double __fabsl(long double); extern "C" double fabs(double); extern "C" float fabsf(float); extern "C" long double fabsl(long double);


extern "C" double __floor(double); extern "C" float __floorf(float); extern "C" long double __floorl(long double); extern "C" double floor(double); extern "C" float floorf(float); extern "C" long double floorl(long double);


extern "C" double __fmod(double, double); extern "C" float __fmodf(float, float); extern "C" long double __fmodl(long double, long double); extern "C" double fmod(double, double); extern "C" float fmodf(float, float); extern "C" long double fmodl(long double, long double);




extern "C" int __isinf(double); extern "C" int __isinff(float); extern "C" int __isinfl(long double);


extern "C" int __finite(double); extern "C" int __finitef(float); extern "C" int __finitel(long double);

#line 202 "/usr/include/bits/mathcalls.h"
extern "C" int isinf(double); extern "C" int isinff(float); extern "C" int isinfl(long double);


extern "C" int finite(double); extern "C" int finitef(float); extern "C" int finitel(long double);


extern "C" double __drem(double, double); extern "C" float __dremf(float, float); extern "C" long double __dreml(long double, long double); extern "C" double drem(double, double); extern "C" float dremf(float, float); extern "C" long double dreml(long double, long double);



extern "C" double __significand(double); extern "C" float __significandf(float); extern "C" long double __significandl(long double); extern "C" double significand(double); extern "C" float significandf(float); extern "C" long double significandl(long double);

#line 218 "/usr/include/bits/mathcalls.h"
extern "C" double __copysign(double, double); extern "C" float __copysignf(float, float); extern "C" long double __copysignl(long double, long double); extern "C" double copysign(double, double); extern "C" float copysignf(float, float); extern "C" long double copysignl(long double, long double);

#line 231 "/usr/include/bits/mathcalls.h"
extern "C" int __isnan(double); extern "C" int __isnanf(float); extern "C" int __isnanl(long double);



extern "C" int isnan(double); extern "C" int isnanf(float); extern "C" int isnanl(long double);


extern "C" double __j0(double); extern "C" float __j0f(float); extern "C" long double __j0l(long double); extern "C" double j0(double); extern "C" float j0f(float); extern "C" long double j0l(long double);
extern "C" double __j1(double); extern "C" float __j1f(float); extern "C" long double __j1l(long double); extern "C" double j1(double); extern "C" float j1f(float); extern "C" long double j1l(long double);
extern "C" double __jn(int, double); extern "C" float __jnf(int, float); extern "C" long double __jnl(int, long double); extern "C" double jn(int, double); extern "C" float jnf(int, float); extern "C" long double jnl(int, long double);
extern "C" double __y0(double); extern "C" float __y0f(float); extern "C" long double __y0l(long double); extern "C" double y0(double); extern "C" float y0f(float); extern "C" long double y0l(long double);
extern "C" double __y1(double); extern "C" float __y1f(float); extern "C" long double __y1l(long double); extern "C" double y1(double); extern "C" float y1f(float); extern "C" long double y1l(long double);
extern "C" double __yn(int, double); extern "C" float __ynf(int, float); extern "C" long double __ynl(int, long double); extern "C" double yn(int, double); extern "C" float ynf(int, float); extern "C" long double ynl(int, long double);

#line 250 "/usr/include/bits/mathcalls.h"
extern "C" double __erf(double); extern "C" float __erff(float); extern "C" long double __erfl(long double); extern "C" double erf(double); extern "C" float erff(float); extern "C" long double erfl(long double);
extern "C" double __erfc(double); extern "C" float __erfcf(float); extern "C" long double __erfcl(long double); extern "C" double erfc(double); extern "C" float erfcf(float); extern "C" long double erfcl(long double);
extern "C" double __lgamma(double); extern "C" float __lgammaf(float); extern "C" long double __lgammal(long double); extern "C" double lgamma(double); extern "C" float lgammaf(float); extern "C" long double lgammal(long double);

#line 265 "/usr/include/bits/mathcalls.h"
extern "C" double __gamma(double); extern "C" float __gammaf(float); extern "C" long double __gammal(long double); extern "C" double gamma(double); extern "C" float gammaf(float); extern "C" long double gammal(long double);

#line 272 "/usr/include/bits/mathcalls.h"
extern "C" double __lgamma_r(double, int *); extern "C" float __lgammaf_r(float, int *); extern "C" long double __lgammal_r(long double, int *); extern "C" double lgamma_r(double, int *); extern "C" float lgammaf_r(float, int *); extern "C" long double lgammal_r(long double, int *);

#line 280 "/usr/include/bits/mathcalls.h"
extern "C" double __rint(double); extern "C" float __rintf(float); extern "C" long double __rintl(long double); extern "C" double rint(double); extern "C" float rintf(float); extern "C" long double rintl(long double);


extern "C" double __nextafter(double, double); extern "C" float __nextafterf(float, float); extern "C" long double __nextafterl(long double, long double); extern "C" double nextafter(double, double); extern "C" float nextafterf(float, float); extern "C" long double nextafterl(long double, long double);

#line 289 "/usr/include/bits/mathcalls.h"
extern "C" double __remainder(double, double); extern "C" float __remainderf(float, float); extern "C" long double __remainderl(long double, long double); extern "C" double remainder(double, double); extern "C" float remainderf(float, float); extern "C" long double remainderl(long double, long double);



extern "C" double __scalbn(double, int); extern "C" float __scalbnf(float, int); extern "C" long double __scalbnl(long double, int); extern "C" double scalbn(double, int); extern "C" float scalbnf(float, int); extern "C" long double scalbnl(long double, int);



extern "C" int __ilogb(double); extern "C" int __ilogbf(float); extern "C" int __ilogbl(long double); extern "C" int ilogb(double); extern "C" int ilogbf(float); extern "C" int ilogbl(long double);

#line 364 "/usr/include/bits/mathcalls.h"
extern "C" double __scalb(double, double); extern "C" float __scalbf(float, float); extern "C" long double __scalbl(long double, long double); extern "C" double scalb(double, double); extern "C" float scalbf(float, float); extern "C" long double scalbl(long double, long double);

#line 27 "/usr/include/bits/sys_errlist.h"
extern int sys_nerr;
extern const char *const sys_errlist[];

#line 343 "/usr/include/libio.h"
extern struct _IO_FILE_plus _IO_2_1_stdin_;
extern struct _IO_FILE_plus _IO_2_1_stdout_;
extern struct _IO_FILE_plus _IO_2_1_stderr_;

#line 413 "/usr/include/libio.h"
extern "C" int __underflow(struct _IO_FILE *);
extern "C" int __uflow(struct _IO_FILE *);
extern "C" int __overflow(struct _IO_FILE *, int);
extern "C" unsigned int __wunderflow(struct _IO_FILE *);
extern "C" unsigned int __wuflow(struct _IO_FILE *);
extern "C" unsigned int __woverflow(struct _IO_FILE *, unsigned int);

#line 451 "/usr/include/libio.h"
extern "C" int _IO_getc(struct _IO_FILE *);
extern "C" int _IO_putc(int, struct _IO_FILE *);
extern "C" int _IO_feof(struct _IO_FILE *);
extern "C" int _IO_ferror(struct _IO_FILE *);

extern "C" int _IO_peekc_locked(struct _IO_FILE *);

#line 462 "/usr/include/libio.h"
extern "C" void _IO_flockfile(struct _IO_FILE *);
extern "C" void _IO_funlockfile(struct _IO_FILE *);
extern "C" int _IO_ftrylockfile(struct _IO_FILE *);

#line 481 "/usr/include/libio.h"
extern "C" int _IO_vfscanf(struct _IO_FILE *, const char *, void *, int *);

extern "C" int _IO_vfprintf(struct _IO_FILE *, const char *, void *);

extern "C" int _IO_padn(struct _IO_FILE *, int, int);
extern "C" unsigned int _IO_sgetn(struct _IO_FILE *, void *, unsigned int);

extern "C" __quad_t _IO_seekoff(struct _IO_FILE *, __quad_t, int, int);
extern "C" __quad_t _IO_seekpos(struct _IO_FILE *, __quad_t, int);

extern "C" void _IO_free_backup_area(struct _IO_FILE *);

#line 157 "/usr/include/math.h"
extern int signgam;

#line 296 "/usr/include/math.h"
extern _LIB_VERSION_TYPE _LIB_VERSION;

#line 322 "/usr/include/math.h"
extern "C" int matherr(struct exception *);

#line 142 "/usr/include/stdio.h"
extern struct _IO_FILE *stdin;
extern struct _IO_FILE *stdout;
extern struct _IO_FILE *stderr;

#line 154 "/usr/include/stdio.h"
extern "C" int remove(const char *);

extern "C" int rename(const char *, const char *);

#line 171 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *tmpfile(void);

#line 185 "/usr/include/stdio.h"
extern "C" char *tmpnam(char *);

#line 191 "/usr/include/stdio.h"
extern "C" char *tmpnam_r(char *);

#line 203 "/usr/include/stdio.h"
extern "C" char *tempnam(const char *, const char *);

#line 213 "/usr/include/stdio.h"
extern "C" int fclose(struct _IO_FILE *);




extern "C" int fflush(struct _IO_FILE *);

#line 228 "/usr/include/stdio.h"
extern "C" int fflush_unlocked(struct _IO_FILE *);

#line 248 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fopen(const char *, const char *);

#line 254 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *freopen(const char *, const char *, struct _IO_FILE *);

#line 280 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *fdopen(int, const char *);

#line 303 "/usr/include/stdio.h"
extern "C" void setbuf(struct _IO_FILE *, char *);



extern "C" int setvbuf(struct _IO_FILE *, char *, int, unsigned int);

#line 314 "/usr/include/stdio.h"
extern "C" void setbuffer(struct _IO_FILE *, char *, unsigned int);



extern "C" void setlinebuf(struct _IO_FILE *);

#line 327 "/usr/include/stdio.h"
extern "C" int fprintf(struct _IO_FILE *, const char *, ...);

#line 333 "/usr/include/stdio.h"
extern "C" int printf(const char *, ...);

extern "C" int sprintf(char *, const char *, ...);

#line 342 "/usr/include/stdio.h"
extern "C" int vfprintf(struct _IO_FILE *, const char *, void *);

#line 348 "/usr/include/stdio.h"
extern "C" int vprintf(const char *, void *);

extern "C" int vsprintf(char *, const char *, void *);

#line 357 "/usr/include/stdio.h"
extern "C" int snprintf(char *, unsigned int, const char *, ...);



extern "C" int vsnprintf(char *, unsigned int, const char *, void *);

#line 399 "/usr/include/stdio.h"
extern "C" int fscanf(struct _IO_FILE *, const char *, ...);

#line 405 "/usr/include/stdio.h"
extern "C" int scanf(const char *, ...);

extern "C" int sscanf(const char *, const char *, ...);

#line 441 "/usr/include/stdio.h"
extern "C" int fgetc(struct _IO_FILE *);
extern "C" int getc(struct _IO_FILE *);

#line 448 "/usr/include/stdio.h"
extern "C" int getchar(void);

#line 460 "/usr/include/stdio.h"
extern "C" int getc_unlocked(struct _IO_FILE *);
extern "C" int getchar_unlocked(void);

#line 471 "/usr/include/stdio.h"
extern "C" int fgetc_unlocked(struct _IO_FILE *);

#line 483 "/usr/include/stdio.h"
extern "C" int fputc(int, struct _IO_FILE *);
extern "C" int putc(int, struct _IO_FILE *);

#line 490 "/usr/include/stdio.h"
extern "C" int putchar(int);

#line 504 "/usr/include/stdio.h"
extern "C" int fputc_unlocked(int, struct _IO_FILE *);

#line 512 "/usr/include/stdio.h"
extern "C" int putc_unlocked(int, struct _IO_FILE *);
extern "C" int putchar_unlocked(int);

#line 520 "/usr/include/stdio.h"
extern "C" int getw(struct _IO_FILE *);


extern "C" int putw(int, struct _IO_FILE *);

#line 532 "/usr/include/stdio.h"
extern "C" char *fgets(char *, int, struct _IO_FILE *);

#line 540 "/usr/include/stdio.h"
extern "C" char *gets(char *);

#line 590 "/usr/include/stdio.h"
extern "C" int fputs(const char *, struct _IO_FILE *);

#line 596 "/usr/include/stdio.h"
extern "C" int puts(const char *);

#line 603 "/usr/include/stdio.h"
extern "C" int ungetc(int, struct _IO_FILE *);

#line 610 "/usr/include/stdio.h"
extern "C" unsigned int fread(void *, unsigned int, unsigned int, struct _IO_FILE *);

#line 616 "/usr/include/stdio.h"
extern "C" unsigned int fwrite(const void *, unsigned int, unsigned int, struct _IO_FILE *);

#line 638 "/usr/include/stdio.h"
extern "C" unsigned int fread_unlocked(void *, unsigned int, unsigned int, struct _IO_FILE *);

extern "C" unsigned int fwrite_unlocked(const void *, unsigned int, unsigned int, struct _IO_FILE *);

#line 650 "/usr/include/stdio.h"
extern "C" int fseek(struct _IO_FILE *, long int, int);




extern "C" long int ftell(struct _IO_FILE *);




extern "C" void rewind(struct _IO_FILE *);

#line 674 "/usr/include/stdio.h"
extern "C" int fseeko(struct _IO_FILE *, long int, int);




extern "C" long int ftello(struct _IO_FILE *);

#line 699 "/usr/include/stdio.h"
extern "C" int fgetpos(struct _IO_FILE *, _G_fpos_t *);




extern "C" int fsetpos(struct _IO_FILE *, const _G_fpos_t *);

#line 727 "/usr/include/stdio.h"
extern "C" void clearerr(struct _IO_FILE *);

extern "C" int feof(struct _IO_FILE *);

extern "C" int ferror(struct _IO_FILE *);




extern "C" void clearerr_unlocked(struct _IO_FILE *);
extern "C" int feof_unlocked(struct _IO_FILE *);
extern "C" int ferror_unlocked(struct _IO_FILE *);

#line 747 "/usr/include/stdio.h"
extern "C" void perror(const char *);

#line 759 "/usr/include/stdio.h"
extern "C" int fileno(struct _IO_FILE *);




extern "C" int fileno_unlocked(struct _IO_FILE *);

#line 774 "/usr/include/stdio.h"
extern "C" struct _IO_FILE *popen(const char *, const char *);

#line 780 "/usr/include/stdio.h"
extern "C" int pclose(struct _IO_FILE *);

#line 786 "/usr/include/stdio.h"
extern "C" char *ctermid(char *);

#line 814 "/usr/include/stdio.h"
extern "C" void flockfile(struct _IO_FILE *);



extern "C" int ftrylockfile(struct _IO_FILE *);


extern "C" void funlockfile(struct _IO_FILE *);

#line 140 "/usr/include/stdlib.h"
extern "C" unsigned int __ctype_get_mb_cur_max(void);




extern "C" double atof(const char *);


extern "C" int atoi(const char *);


extern "C" long int atol(const char *);

#line 165 "/usr/include/stdlib.h"
extern "C" double strtod(const char *, char **);

#line 184 "/usr/include/stdlib.h"
extern "C" long int strtol(const char *, char **, int);



extern "C" unsigned long int strtoul(const char *, char **, int);

#line 279 "/usr/include/stdlib.h"
extern "C" double __strtod_internal(const char *, char **, int);


extern "C" float __strtof_internal(const char *, char **, int);


extern "C" long double __strtold_internal(const char *, char **, int);




extern "C" long int __strtol_internal(const char *, char **, int, int);

#line 297 "/usr/include/stdlib.h"
extern "C" unsigned long int __strtoul_internal(const char *, char **, int, int);

#line 429 "/usr/include/stdlib.h"
extern "C" char *l64a(long int);


extern "C" long int a64l(const char *);

#line 445 "/usr/include/stdlib.h"
extern "C" long int random(void);


extern "C" void srandom(unsigned int);

#line 454 "/usr/include/stdlib.h"
extern "C" char *initstate(unsigned int, char *, unsigned int);




extern "C" char *setstate(char *);

#line 478 "/usr/include/stdlib.h"
extern "C" int random_r(struct random_data *, int *);


extern "C" int srandom_r(unsigned int, struct random_data *);


extern "C" int initstate_r(unsigned int, char *, unsigned int, struct random_data *);




extern "C" int setstate_r(char *, struct random_data *);

#line 498 "/usr/include/stdlib.h"
extern "C" int rand(void);

extern "C" void srand(unsigned int);




extern "C" int rand_r(unsigned int *);

#line 513 "/usr/include/stdlib.h"
extern "C" double drand48(void);
extern "C" double erand48(unsigned short int [3]);


extern "C" long int lrand48(void);
extern "C" long int nrand48(unsigned short int [3]);



extern "C" long int mrand48(void);
extern "C" long int jrand48(unsigned short int [3]);



extern "C" void srand48(long int);
extern "C" unsigned short int *seed48(unsigned short int [3]);

extern "C" void lcong48(unsigned short int [7]);

#line 546 "/usr/include/stdlib.h"
extern "C" int drand48_r(struct drand48_data *, double *);

extern "C" int erand48_r(unsigned short int [3], struct drand48_data *, double *);




extern "C" int lrand48_r(struct drand48_data *, long int *);


extern "C" int nrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 562 "/usr/include/stdlib.h"
extern "C" int mrand48_r(struct drand48_data *, long int *);


extern "C" int jrand48_r(unsigned short int [3], struct drand48_data *, long int *);

#line 571 "/usr/include/stdlib.h"
extern "C" int srand48_r(long int, struct drand48_data *);


extern "C" int seed48_r(unsigned short int [3], struct drand48_data *);


extern "C" int lcong48_r(unsigned short int [7], struct drand48_data *);

#line 589 "/usr/include/stdlib.h"
extern "C" void *malloc(unsigned int);

extern "C" void *calloc(unsigned int, unsigned int);

#line 600 "/usr/include/stdlib.h"
extern "C" void *realloc(void *, unsigned int);


extern "C" void free(void *);




extern "C" void cfree(void *);

#line 617 "/usr/include/stdlib.h"
extern "C" void *valloc(unsigned int);




extern "C" int posix_memalign(void **, unsigned int, unsigned int);

#line 628 "/usr/include/stdlib.h"
extern "C" void abort(void);



extern "C" int atexit(void (*)(void));

#line 638 "/usr/include/stdlib.h"
extern "C" int on_exit(void (*)(int, void *), void *);

#line 646 "/usr/include/stdlib.h"
extern "C" void exit(int);

#line 660 "/usr/include/stdlib.h"
extern "C" char *getenv(const char *);




extern "C" char *__secure_getenv(const char *);

#line 672 "/usr/include/stdlib.h"
extern "C" int putenv(char *);

#line 678 "/usr/include/stdlib.h"
extern "C" int setenv(const char *, const char *, int);



extern "C" int unsetenv(const char *);

#line 689 "/usr/include/stdlib.h"
extern "C" int clearenv(void);

#line 698 "/usr/include/stdlib.h"
extern "C" char *mktemp(char *);

#line 709 "/usr/include/stdlib.h"
extern "C" int mkstemp(char *);

#line 729 "/usr/include/stdlib.h"
extern "C" char *mkdtemp(char *);

#line 738 "/usr/include/stdlib.h"
extern "C" int system(const char *);

#line 756 "/usr/include/stdlib.h"
extern "C" char *realpath(const char *, char *);

#line 774 "/usr/include/stdlib.h"
extern "C" void *bsearch(const void *, const void *, unsigned int, unsigned int, int (*)(const void *, const void *));

#line 780 "/usr/include/stdlib.h"
extern "C" void qsort(void *, unsigned int, unsigned int, int (*)(const void *, const void *));




extern "C" int abs(int);
extern "C" long int labs(long int);

#line 799 "/usr/include/stdlib.h"
extern "C" div_t div(int, int);

extern "C" ldiv_t ldiv(long int, long int);

#line 821 "/usr/include/stdlib.h"
extern "C" char *ecvt(double, int, int *, int *);

#line 827 "/usr/include/stdlib.h"
extern "C" char *fcvt(double, int, int *, int *);

#line 833 "/usr/include/stdlib.h"
extern "C" char *gcvt(double, int, char *);

#line 839 "/usr/include/stdlib.h"
extern "C" char *qecvt(long double, int, int *, int *);


extern "C" char *qfcvt(long double, int, int *, int *);


extern "C" char *qgcvt(long double, int, char *);

#line 851 "/usr/include/stdlib.h"
extern "C" int ecvt_r(double, int, int *, int *, char *, unsigned int);


extern "C" int fcvt_r(double, int, int *, int *, char *, unsigned int);



extern "C" int qecvt_r(long double, int, int *, int *, char *, unsigned int);



extern "C" int qfcvt_r(long double, int, int *, int *, char *, unsigned int);

#line 873 "/usr/include/stdlib.h"
extern "C" int mblen(const char *, unsigned int);


extern "C" int mbtowc(long int *, const char *, unsigned int);



extern "C" int wctomb(char *, long int);



extern "C" unsigned int mbstowcs(long int *, const char *, unsigned int);


extern "C" unsigned int wcstombs(char *, const long int *, unsigned int);

#line 898 "/usr/include/stdlib.h"
extern "C" int rpmatch(const char *);

#line 926 "/usr/include/stdlib.h"
extern "C" int posix_openpt(int);

#line 961 "/usr/include/stdlib.h"
extern "C" int getloadavg(double [], int);

#line 38 "/usr/include/string.h"
extern "C" void *memcpy(void *, const void *, unsigned int);




extern "C" void *memmove(void *, const void *, unsigned int);

#line 51 "/usr/include/string.h"
extern "C" void *memccpy(void *, const void *, int, unsigned int);

#line 59 "/usr/include/string.h"
extern "C" void *memset(void *, int, unsigned int);


extern "C" int memcmp(const void *, const void *, unsigned int);



extern "C" void *memchr(const void *, int, unsigned int);

#line 84 "/usr/include/string.h"
extern "C" char *strcpy(char *, const char *);


extern "C" char *strncpy(char *, const char *, unsigned int);




extern "C" char *strcat(char *, const char *);


extern "C" char *strncat(char *, const char *, unsigned int);



extern "C" int strcmp(const char *, const char *);


extern "C" int strncmp(const char *, const char *, unsigned int);



extern "C" int strcoll(const char *, const char *);


extern "C" unsigned int strxfrm(char *, const char *, unsigned int);

#line 130 "/usr/include/string.h"
extern "C" char *strdup(const char *);

#line 167 "/usr/include/string.h"
extern "C" char *strchr(const char *, int);


extern "C" char *strrchr(const char *, int);

#line 184 "/usr/include/string.h"
extern "C" unsigned int strcspn(const char *, const char *);



extern "C" unsigned int strspn(const char *, const char *);


extern "C" char *strpbrk(const char *, const char *);


extern "C" char *strstr(const char *, const char *);




extern "C" char *strtok(char *, const char *);

#line 205 "/usr/include/string.h"
extern "C" char *__strtok_r(char *, const char *, char **);




extern "C" char *strtok_r(char *, const char *, char **);

#line 242 "/usr/include/string.h"
extern "C" unsigned int strlen(const char *);

#line 256 "/usr/include/string.h"
extern "C" char *strerror(int);

#line 274 "/usr/include/string.h"
extern "C" int __xpg_strerror_r(int, char *, unsigned int);

#line 288 "/usr/include/string.h"
extern "C" void __bzero(void *, unsigned int);



extern "C" void bcopy(const void *, void *, unsigned int);



extern "C" void bzero(void *, unsigned int);


extern "C" int bcmp(const void *, const void *, unsigned int);



extern "C" char *index(const char *, int);



extern "C" char *rindex(const char *, int);




extern "C" int ffs(int);

#line 325 "/usr/include/string.h"
extern "C" int strcasecmp(const char *, const char *);



extern "C" int strncasecmp(const char *, const char *, unsigned int);

#line 348 "/usr/include/string.h"
extern "C" char *strsep(char **, const char *);

#line 109 "/usr/include/sys/select.h"
extern "C" int select(int, fd_set *, fd_set *, fd_set *, struct timeval *);

#line 121 "/usr/include/sys/select.h"
extern "C" int pselect(int, fd_set *, fd_set *, fd_set *, const struct timespec *, const __sigset_t *);

#line 49 "/usr/local/packages/sce-20100908/inc/sim.sh"
extern const int _SPECC_VERSION_MAJOR;
extern const int _SPECC_VERSION_MINOR;

#line 42 "/usr/local/packages/sce-20100908/inc/sim/bit.sh"
extern "C" char *bit2str(unsigned int, char *, ...);

#line 48 "/usr/local/packages/sce-20100908/inc/sim/bit.sh"
extern "C" char *ubit2str(unsigned int, char *, ...);




extern "C" void str2bit(unsigned int, const char *, ...);




extern "C" void str2ubit(unsigned int, const char *, ...);

#line 41 "/usr/local/packages/sce-20100908/inc/sim/longlong.sh"
extern "C" char *ll2str(unsigned int, char *, long long int);




extern "C" char *ull2str(unsigned int, char *, unsigned long long int);




extern "C" long long int str2ll(unsigned int, const char *);



extern "C" unsigned long long int str2ull(unsigned int, const char *);

#line 73 "/usr/local/packages/sce-20100908/inc/sim/time.sh"
extern "C" unsigned long long int now(void);

extern "C" unsigned long long int delta(void);


extern "C" const char *time2str(char [21], unsigned long long int);



extern "C" unsigned long long int str2time(const char *);

#line 3347 "susan_edge_detector.h"
void _scc_range_check(unsigned long long, unsigned long long, unsigned long long, bool, unsigned long long, bool, const char *, const char *, const char *, unsigned int);
void _scc_bit4_err_handle(const _bit4&);

//////////////////////////////////////////////////////////////////////
// End of file susan_edge_detector.h
//////////////////////////////////////////////////////////////////////
